version: '3.8'

services:
  auth-service:
    container_name: auth-service-container
    restart: always
    build:
      context: ./backend/auth-service/
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
    develop : 
      watch : 
        - path : ./backend/auth-service/package.json
          action : rebuild
        - path : ./backend/auth-service/package-lock.json
          action : rebuild
        - path : ./backend/auth-service
          target : /app
          action : sync
    ports:
      - 8080:8080
    volumes:
      - ./backend/auth-service:/app
      - /app/node_modules
    command: npm run start
  
  web:
    container_name: frontend-container
    restart : always
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 5173:5173
    volumes:
      # - ./frontend:/app
      - /app/node_modules
    develop:
      watch:
        - path: ./frontend/package.json
          action: rebuild
        - path: ./frontend/package-lock.json
          action: rebuild
        - path: ./frontend
          target : /app
          action: sync+restart
    command: npm run build
    

